---
- name: Terrabot wakes up
  hosts: localhost
  become: no

  vars:
    pwd: "{{ lookup('env', 'PWD') }}"
    target_dir: "{{ pwd }}/target"
    layers_dir: "{{ pwd }}/terraform"
    tf_upgrade: true
    dry_run: false
    backend_reconfigure: true

  pre_tasks:
    - name: Clone remote stack
      include_tasks: "{{ playbook_dir }}/inc/_clone.yml"
      when:
        - remote_stack_url is defined
        - remote_stack_version is defined

    #- import_tasks: "{{ playbook_dir }}/inc/_setup.yml"

  tasks:
    - import_tasks: "{{ playbook_dir }}/inc/_tf_{{ tfaction }}.yml"

  post_tasks:

    - name: Clean remote stack
      file:
        path: "{{ taco_remote_stack_clone_dir.path }}"
        state: absent
      when:
        - remote_stack_url is defined
        - remote_stack_version is defined
