---
- hosts: localhost
  become: no
  gather_facts: no

  vars:
    pwd: "{{ lookup('env', 'PWD') }}"
    target_dir: "{{ pwd }}/target"
    layers_dir: "{{ pwd }}/terraform"
    terrabot_vars: "{{ {} }}"
    deploy_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
    tf_upgrade: true
    dry_run: false
    backend_reconfigure: true

  pre_tasks:
    - sts_assume_role:
        role_arn: "{{ initial_role }}"
        role_session_name: "{{ initial_role.split('/')[-1] }}"
      register: initial_role_credentials
      when: assume_initial_role|default(false)

    - include_tasks: "{{ playbook_dir }}/inc/_clone.yml"
      when:
        - remote_stack_url is defined
        - remote_stack_version is defined

    - import_tasks: "{{ playbook_dir }}/inc/_setup.yml"

  tasks:
    - include_tasks: "{{ playbook_dir }}/inc/_tf_{{ tfaction }}.yml"

  post_tasks:
    - include_tasks: "{{ post_tasks_file }}"
      when: post_tasks_file is defined

    - import_tasks: "{{ playbook_dir }}/inc/_teardown.yml"

    - shell: >-
        rm -rf {{ terrabot_remote_stack_clone_dir.path }}
      when:
        - remote_stack_url is defined
        - remote_stack_version is defined